name: Daily Dump Data to MongoDB

on:
  schedule:
    - cron: "0 9 * * *"  # This sets the job to run daily at 9am UTC (moscow 12pm)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  dump_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo

      - name: Run data dump script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}  # Use the MongoDB URI secret
        run: |
          python Analytics/data_dump.py

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add data.json
          git commit -m "Clear data.json after dumping data to MongoDB"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token to workflows
