name: Hourly Workflow

on:
  schedule:
    - cron: '30 * * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Python dependencies
        run: python -m pip install selenium

      - name: Run Python script
        run: python Analytics/hour_sampling.py
