name: Hourly Workflow

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install Python dependencies
        run: python -m pip install selenium

      - name: Run Python script
        run: python Analytics/hour_sampling.py

      - name: Write log to file
        run: echo "This is a log message." > scraper.logs

      - name: Add changes to Git
        run: |
          git add scraper.logs data.json
          git commit -m "Update logs and data"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
