name: Hourly Workflow

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Install Python dependencies
        run: python -m pip install selenium

      - name: Debug - Print working directory
        run: |
          echo Current Directory:
          cd
          echo Directory Contents:
          dir

      - name: Run Python script
        run: python Analytics/hour_sampling.py
