name: Hourly Workflow

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Debug - List all files in the repository
        run: |
          echo Listing all files:
          dir /s /b
        
      - name: Install Python dependencies
        run: python -m pip install selenium

      - name: Run Python script
        run: python Analytics/hour_sampling.py
