name: Hourly Workflow

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    outputs:
      log_content: ${{ steps.generate_log.outputs.log_content }}

    steps:
      - name: Generate log content
        id: generate_log
        run: |
          echo "This is a log message."
          echo "::set-output name=log_content::This is a log message."

      - name: Install Python dependencies
        run: python -m pip install selenium

      - name: Run Python script
        run: python Analytics/hour_sampling.py

      - name: Write log to file
        if: always()
        run: echo "${{ needs.build.outputs.log_content }}" > scraper.logs

      - name: Upload logfile as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: scraper
          path: scraper.logs
