name: Hourly Workflow

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Debug - List root directory
        run: |
          echo Root Directory Contents:
          dir

      - name: Change permissions of root directory
        run: |
          cd ${{ github.workspace }}
          chmod -R 777 .

      - name: Debug - List checked out repository
        run: |
          echo Repository Directory Contents:
          dir ${{ github.workspace }}
        
      - name: Install Python dependencies
        run: python -m pip install selenium

      - name: Run Python script
        run: python Analytics/hour_sampling.py
